server:
  port: 8083
spring:
  #数据库连接配置
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: ql120808
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    # content-type: text/html
    enabled: true
    encoding: UTF-8
    # excluded-view-names:
    # mode: HTML5
    # prefix: /templates/
    # suffix: .html
    # template-resolver-order:
    # view-names:
  messages:
    basename: messages
    fallback-to-system-locale: false
    cache-duration: 1
    encoding: UTF-8

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: ly.jp.application.model.entity
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true

