package ly.jp.application.mapper.auto;

import java.util.List;
import ly.jp.application.model.entity.Usermst;
import ly.jp.application.model.entity.UsermstExample;
import org.apache.ibatis.annotations.Param;

public interface UsermstMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.UserMst
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    int countByExample(UsermstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.UserMst
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    int deleteByExample(UsermstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.UserMst
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    int deleteByPrimaryKey(String userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.UserMst
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    int insert(Usermst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.UserMst
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    int insertSelective(Usermst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.UserMst
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    List<Usermst> selectByExample(UsermstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.UserMst
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    Usermst selectByPrimaryKey(String userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.UserMst
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    int updateByExampleSelective(@Param("record") Usermst record, @Param("example") UsermstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.UserMst
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    int updateByExample(@Param("record") Usermst record, @Param("example") UsermstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.UserMst
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    int updateByPrimaryKeySelective(Usermst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.UserMst
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    int updateByPrimaryKey(Usermst record);
}