package ly.jp.application.mapper.auto;

import java.util.List;
import ly.jp.application.model.entity.Userdetail;
import ly.jp.application.model.entity.UserdetailExample;
import org.apache.ibatis.annotations.Param;

public interface UserdetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.UserDetail
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    int countByExample(UserdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.UserDetail
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    int deleteByExample(UserdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.UserDetail
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    int insert(Userdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.UserDetail
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    int insertSelective(Userdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.UserDetail
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    List<Userdetail> selectByExampleWithBLOBs(UserdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.UserDetail
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    List<Userdetail> selectByExample(UserdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.UserDetail
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    int updateByExampleSelective(@Param("record") Userdetail record, @Param("example") UserdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.UserDetail
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    int updateByExampleWithBLOBs(@Param("record") Userdetail record, @Param("example") UserdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.UserDetail
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    int updateByExample(@Param("record") Userdetail record, @Param("example") UserdetailExample example);
}