package ly.jp.application.model.entity;

public class Testtbl {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.testTbl.id
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.testTbl.name
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.testTbl.testclm
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    private Short testclm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.testTbl.id
     *
     * @return the value of public.testTbl.id
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.testTbl.id
     *
     * @param id the value for public.testTbl.id
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.testTbl.name
     *
     * @return the value of public.testTbl.name
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.testTbl.name
     *
     * @param name the value for public.testTbl.name
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.testTbl.testclm
     *
     * @return the value of public.testTbl.testclm
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public Short getTestclm() {
        return testclm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.testTbl.testclm
     *
     * @param testclm the value for public.testTbl.testclm
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public void setTestclm(Short testclm) {
        this.testclm = testclm;
    }
}