package ly.jp.application.model.entity;

public class Timesheets {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.timeSheets.userID
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    private String userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.timeSheets.userID
     *
     * @return the value of public.timeSheets.userID
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.timeSheets.userID
     *
     * @param userid the value for public.timeSheets.userID
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }
}