package ly.jp.application.model.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class UserdetailExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.UserDetail
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.UserDetail
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.UserDetail
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.UserDetail
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public UserdetailExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.UserDetail
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.UserDetail
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.UserDetail
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.UserDetail
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.UserDetail
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.UserDetail
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.UserDetail
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.UserDetail
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.UserDetail
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.UserDetail
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.UserDetail
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andUseridIsNull() {
            addCriterion("\"userID\" is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("\"userID\" is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(String value) {
            addCriterion("\"userID\" =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(String value) {
            addCriterion("\"userID\" <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(String value) {
            addCriterion("\"userID\" >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(String value) {
            addCriterion("\"userID\" >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(String value) {
            addCriterion("\"userID\" <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(String value) {
            addCriterion("\"userID\" <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLike(String value) {
            addCriterion("\"userID\" like", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotLike(String value) {
            addCriterion("\"userID\" not like", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<String> values) {
            addCriterion("\"userID\" in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<String> values) {
            addCriterion("\"userID\" not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(String value1, String value2) {
            addCriterion("\"userID\" between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(String value1, String value2) {
            addCriterion("\"userID\" not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("\"userName\" is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("\"userName\" is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("\"userName\" =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("\"userName\" <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("\"userName\" >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("\"userName\" >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("\"userName\" <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("\"userName\" <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("\"userName\" like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("\"userName\" not like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("\"userName\" in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("\"userName\" not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("\"userName\" between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("\"userName\" not between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andKatakananameIsNull() {
            addCriterion("\"katakanaName\" is null");
            return (Criteria) this;
        }

        public Criteria andKatakananameIsNotNull() {
            addCriterion("\"katakanaName\" is not null");
            return (Criteria) this;
        }

        public Criteria andKatakananameEqualTo(String value) {
            addCriterion("\"katakanaName\" =", value, "katakananame");
            return (Criteria) this;
        }

        public Criteria andKatakananameNotEqualTo(String value) {
            addCriterion("\"katakanaName\" <>", value, "katakananame");
            return (Criteria) this;
        }

        public Criteria andKatakananameGreaterThan(String value) {
            addCriterion("\"katakanaName\" >", value, "katakananame");
            return (Criteria) this;
        }

        public Criteria andKatakananameGreaterThanOrEqualTo(String value) {
            addCriterion("\"katakanaName\" >=", value, "katakananame");
            return (Criteria) this;
        }

        public Criteria andKatakananameLessThan(String value) {
            addCriterion("\"katakanaName\" <", value, "katakananame");
            return (Criteria) this;
        }

        public Criteria andKatakananameLessThanOrEqualTo(String value) {
            addCriterion("\"katakanaName\" <=", value, "katakananame");
            return (Criteria) this;
        }

        public Criteria andKatakananameLike(String value) {
            addCriterion("\"katakanaName\" like", value, "katakananame");
            return (Criteria) this;
        }

        public Criteria andKatakananameNotLike(String value) {
            addCriterion("\"katakanaName\" not like", value, "katakananame");
            return (Criteria) this;
        }

        public Criteria andKatakananameIn(List<String> values) {
            addCriterion("\"katakanaName\" in", values, "katakananame");
            return (Criteria) this;
        }

        public Criteria andKatakananameNotIn(List<String> values) {
            addCriterion("\"katakanaName\" not in", values, "katakananame");
            return (Criteria) this;
        }

        public Criteria andKatakananameBetween(String value1, String value2) {
            addCriterion("\"katakanaName\" between", value1, value2, "katakananame");
            return (Criteria) this;
        }

        public Criteria andKatakananameNotBetween(String value1, String value2) {
            addCriterion("\"katakanaName\" not between", value1, value2, "katakananame");
            return (Criteria) this;
        }

        public Criteria andSexIsNull() {
            addCriterion("\"sex\" is null");
            return (Criteria) this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("\"sex\" is not null");
            return (Criteria) this;
        }

        public Criteria andSexEqualTo(String value) {
            addCriterion("\"sex\" =", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotEqualTo(String value) {
            addCriterion("\"sex\" <>", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThan(String value) {
            addCriterion("\"sex\" >", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThanOrEqualTo(String value) {
            addCriterion("\"sex\" >=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThan(String value) {
            addCriterion("\"sex\" <", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThanOrEqualTo(String value) {
            addCriterion("\"sex\" <=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLike(String value) {
            addCriterion("\"sex\" like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotLike(String value) {
            addCriterion("\"sex\" not like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexIn(List<String> values) {
            addCriterion("\"sex\" in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotIn(List<String> values) {
            addCriterion("\"sex\" not in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexBetween(String value1, String value2) {
            addCriterion("\"sex\" between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotBetween(String value1, String value2) {
            addCriterion("\"sex\" not between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("\"address\" is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("\"address\" is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("\"address\" =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("\"address\" <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("\"address\" >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("\"address\" >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("\"address\" <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("\"address\" <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("\"address\" like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("\"address\" not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("\"address\" in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("\"address\" not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("\"address\" between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("\"address\" not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAgeIsNull() {
            addCriterion("\"age\" is null");
            return (Criteria) this;
        }

        public Criteria andAgeIsNotNull() {
            addCriterion("\"age\" is not null");
            return (Criteria) this;
        }

        public Criteria andAgeEqualTo(Short value) {
            addCriterion("\"age\" =", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotEqualTo(Short value) {
            addCriterion("\"age\" <>", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThan(Short value) {
            addCriterion("\"age\" >", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThanOrEqualTo(Short value) {
            addCriterion("\"age\" >=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThan(Short value) {
            addCriterion("\"age\" <", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThanOrEqualTo(Short value) {
            addCriterion("\"age\" <=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeIn(List<Short> values) {
            addCriterion("\"age\" in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotIn(List<Short> values) {
            addCriterion("\"age\" not in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeBetween(Short value1, Short value2) {
            addCriterion("\"age\" between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotBetween(Short value1, Short value2) {
            addCriterion("\"age\" not between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andBirthdateIsNull() {
            addCriterion("\"birthdate\" is null");
            return (Criteria) this;
        }

        public Criteria andBirthdateIsNotNull() {
            addCriterion("\"birthdate\" is not null");
            return (Criteria) this;
        }

        public Criteria andBirthdateEqualTo(Date value) {
            addCriterionForJDBCDate("\"birthdate\" =", value, "birthdate");
            return (Criteria) this;
        }

        public Criteria andBirthdateNotEqualTo(Date value) {
            addCriterionForJDBCDate("\"birthdate\" <>", value, "birthdate");
            return (Criteria) this;
        }

        public Criteria andBirthdateGreaterThan(Date value) {
            addCriterionForJDBCDate("\"birthdate\" >", value, "birthdate");
            return (Criteria) this;
        }

        public Criteria andBirthdateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("\"birthdate\" >=", value, "birthdate");
            return (Criteria) this;
        }

        public Criteria andBirthdateLessThan(Date value) {
            addCriterionForJDBCDate("\"birthdate\" <", value, "birthdate");
            return (Criteria) this;
        }

        public Criteria andBirthdateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("\"birthdate\" <=", value, "birthdate");
            return (Criteria) this;
        }

        public Criteria andBirthdateIn(List<Date> values) {
            addCriterionForJDBCDate("\"birthdate\" in", values, "birthdate");
            return (Criteria) this;
        }

        public Criteria andBirthdateNotIn(List<Date> values) {
            addCriterionForJDBCDate("\"birthdate\" not in", values, "birthdate");
            return (Criteria) this;
        }

        public Criteria andBirthdateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("\"birthdate\" between", value1, value2, "birthdate");
            return (Criteria) this;
        }

        public Criteria andBirthdateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("\"birthdate\" not between", value1, value2, "birthdate");
            return (Criteria) this;
        }

        public Criteria andPhonenumericIsNull() {
            addCriterion("\"phonenumeric\" is null");
            return (Criteria) this;
        }

        public Criteria andPhonenumericIsNotNull() {
            addCriterion("\"phonenumeric\" is not null");
            return (Criteria) this;
        }

        public Criteria andPhonenumericEqualTo(Long value) {
            addCriterion("\"phonenumeric\" =", value, "phonenumeric");
            return (Criteria) this;
        }

        public Criteria andPhonenumericNotEqualTo(Long value) {
            addCriterion("\"phonenumeric\" <>", value, "phonenumeric");
            return (Criteria) this;
        }

        public Criteria andPhonenumericGreaterThan(Long value) {
            addCriterion("\"phonenumeric\" >", value, "phonenumeric");
            return (Criteria) this;
        }

        public Criteria andPhonenumericGreaterThanOrEqualTo(Long value) {
            addCriterion("\"phonenumeric\" >=", value, "phonenumeric");
            return (Criteria) this;
        }

        public Criteria andPhonenumericLessThan(Long value) {
            addCriterion("\"phonenumeric\" <", value, "phonenumeric");
            return (Criteria) this;
        }

        public Criteria andPhonenumericLessThanOrEqualTo(Long value) {
            addCriterion("\"phonenumeric\" <=", value, "phonenumeric");
            return (Criteria) this;
        }

        public Criteria andPhonenumericIn(List<Long> values) {
            addCriterion("\"phonenumeric\" in", values, "phonenumeric");
            return (Criteria) this;
        }

        public Criteria andPhonenumericNotIn(List<Long> values) {
            addCriterion("\"phonenumeric\" not in", values, "phonenumeric");
            return (Criteria) this;
        }

        public Criteria andPhonenumericBetween(Long value1, Long value2) {
            addCriterion("\"phonenumeric\" between", value1, value2, "phonenumeric");
            return (Criteria) this;
        }

        public Criteria andPhonenumericNotBetween(Long value1, Long value2) {
            addCriterion("\"phonenumeric\" not between", value1, value2, "phonenumeric");
            return (Criteria) this;
        }

        public Criteria andWechatnumericIsNull() {
            addCriterion("\"weChatnumeric\" is null");
            return (Criteria) this;
        }

        public Criteria andWechatnumericIsNotNull() {
            addCriterion("\"weChatnumeric\" is not null");
            return (Criteria) this;
        }

        public Criteria andWechatnumericEqualTo(String value) {
            addCriterion("\"weChatnumeric\" =", value, "wechatnumeric");
            return (Criteria) this;
        }

        public Criteria andWechatnumericNotEqualTo(String value) {
            addCriterion("\"weChatnumeric\" <>", value, "wechatnumeric");
            return (Criteria) this;
        }

        public Criteria andWechatnumericGreaterThan(String value) {
            addCriterion("\"weChatnumeric\" >", value, "wechatnumeric");
            return (Criteria) this;
        }

        public Criteria andWechatnumericGreaterThanOrEqualTo(String value) {
            addCriterion("\"weChatnumeric\" >=", value, "wechatnumeric");
            return (Criteria) this;
        }

        public Criteria andWechatnumericLessThan(String value) {
            addCriterion("\"weChatnumeric\" <", value, "wechatnumeric");
            return (Criteria) this;
        }

        public Criteria andWechatnumericLessThanOrEqualTo(String value) {
            addCriterion("\"weChatnumeric\" <=", value, "wechatnumeric");
            return (Criteria) this;
        }

        public Criteria andWechatnumericLike(String value) {
            addCriterion("\"weChatnumeric\" like", value, "wechatnumeric");
            return (Criteria) this;
        }

        public Criteria andWechatnumericNotLike(String value) {
            addCriterion("\"weChatnumeric\" not like", value, "wechatnumeric");
            return (Criteria) this;
        }

        public Criteria andWechatnumericIn(List<String> values) {
            addCriterion("\"weChatnumeric\" in", values, "wechatnumeric");
            return (Criteria) this;
        }

        public Criteria andWechatnumericNotIn(List<String> values) {
            addCriterion("\"weChatnumeric\" not in", values, "wechatnumeric");
            return (Criteria) this;
        }

        public Criteria andWechatnumericBetween(String value1, String value2) {
            addCriterion("\"weChatnumeric\" between", value1, value2, "wechatnumeric");
            return (Criteria) this;
        }

        public Criteria andWechatnumericNotBetween(String value1, String value2) {
            addCriterion("\"weChatnumeric\" not between", value1, value2, "wechatnumeric");
            return (Criteria) this;
        }

        public Criteria andMailaddressIsNull() {
            addCriterion("\"mailAddress\" is null");
            return (Criteria) this;
        }

        public Criteria andMailaddressIsNotNull() {
            addCriterion("\"mailAddress\" is not null");
            return (Criteria) this;
        }

        public Criteria andMailaddressEqualTo(String value) {
            addCriterion("\"mailAddress\" =", value, "mailaddress");
            return (Criteria) this;
        }

        public Criteria andMailaddressNotEqualTo(String value) {
            addCriterion("\"mailAddress\" <>", value, "mailaddress");
            return (Criteria) this;
        }

        public Criteria andMailaddressGreaterThan(String value) {
            addCriterion("\"mailAddress\" >", value, "mailaddress");
            return (Criteria) this;
        }

        public Criteria andMailaddressGreaterThanOrEqualTo(String value) {
            addCriterion("\"mailAddress\" >=", value, "mailaddress");
            return (Criteria) this;
        }

        public Criteria andMailaddressLessThan(String value) {
            addCriterion("\"mailAddress\" <", value, "mailaddress");
            return (Criteria) this;
        }

        public Criteria andMailaddressLessThanOrEqualTo(String value) {
            addCriterion("\"mailAddress\" <=", value, "mailaddress");
            return (Criteria) this;
        }

        public Criteria andMailaddressLike(String value) {
            addCriterion("\"mailAddress\" like", value, "mailaddress");
            return (Criteria) this;
        }

        public Criteria andMailaddressNotLike(String value) {
            addCriterion("\"mailAddress\" not like", value, "mailaddress");
            return (Criteria) this;
        }

        public Criteria andMailaddressIn(List<String> values) {
            addCriterion("\"mailAddress\" in", values, "mailaddress");
            return (Criteria) this;
        }

        public Criteria andMailaddressNotIn(List<String> values) {
            addCriterion("\"mailAddress\" not in", values, "mailaddress");
            return (Criteria) this;
        }

        public Criteria andMailaddressBetween(String value1, String value2) {
            addCriterion("\"mailAddress\" between", value1, value2, "mailaddress");
            return (Criteria) this;
        }

        public Criteria andMailaddressNotBetween(String value1, String value2) {
            addCriterion("\"mailAddress\" not between", value1, value2, "mailaddress");
            return (Criteria) this;
        }

        public Criteria andPositionIsNull() {
            addCriterion("\"position\" is null");
            return (Criteria) this;
        }

        public Criteria andPositionIsNotNull() {
            addCriterion("\"position\" is not null");
            return (Criteria) this;
        }

        public Criteria andPositionEqualTo(String value) {
            addCriterion("\"position\" =", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionNotEqualTo(String value) {
            addCriterion("\"position\" <>", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionGreaterThan(String value) {
            addCriterion("\"position\" >", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionGreaterThanOrEqualTo(String value) {
            addCriterion("\"position\" >=", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionLessThan(String value) {
            addCriterion("\"position\" <", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionLessThanOrEqualTo(String value) {
            addCriterion("\"position\" <=", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionLike(String value) {
            addCriterion("\"position\" like", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionNotLike(String value) {
            addCriterion("\"position\" not like", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionIn(List<String> values) {
            addCriterion("\"position\" in", values, "position");
            return (Criteria) this;
        }

        public Criteria andPositionNotIn(List<String> values) {
            addCriterion("\"position\" not in", values, "position");
            return (Criteria) this;
        }

        public Criteria andPositionBetween(String value1, String value2) {
            addCriterion("\"position\" between", value1, value2, "position");
            return (Criteria) this;
        }

        public Criteria andPositionNotBetween(String value1, String value2) {
            addCriterion("\"position\" not between", value1, value2, "position");
            return (Criteria) this;
        }

        public Criteria andNationalityIsNull() {
            addCriterion("\"nationality\" is null");
            return (Criteria) this;
        }

        public Criteria andNationalityIsNotNull() {
            addCriterion("\"nationality\" is not null");
            return (Criteria) this;
        }

        public Criteria andNationalityEqualTo(String value) {
            addCriterion("\"nationality\" =", value, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityNotEqualTo(String value) {
            addCriterion("\"nationality\" <>", value, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityGreaterThan(String value) {
            addCriterion("\"nationality\" >", value, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityGreaterThanOrEqualTo(String value) {
            addCriterion("\"nationality\" >=", value, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityLessThan(String value) {
            addCriterion("\"nationality\" <", value, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityLessThanOrEqualTo(String value) {
            addCriterion("\"nationality\" <=", value, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityLike(String value) {
            addCriterion("\"nationality\" like", value, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityNotLike(String value) {
            addCriterion("\"nationality\" not like", value, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityIn(List<String> values) {
            addCriterion("\"nationality\" in", values, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityNotIn(List<String> values) {
            addCriterion("\"nationality\" not in", values, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityBetween(String value1, String value2) {
            addCriterion("\"nationality\" between", value1, value2, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityNotBetween(String value1, String value2) {
            addCriterion("\"nationality\" not between", value1, value2, "nationality");
            return (Criteria) this;
        }

        public Criteria andMartialstatusIsNull() {
            addCriterion("\"martialStatus\" is null");
            return (Criteria) this;
        }

        public Criteria andMartialstatusIsNotNull() {
            addCriterion("\"martialStatus\" is not null");
            return (Criteria) this;
        }

        public Criteria andMartialstatusEqualTo(Short value) {
            addCriterion("\"martialStatus\" =", value, "martialstatus");
            return (Criteria) this;
        }

        public Criteria andMartialstatusNotEqualTo(Short value) {
            addCriterion("\"martialStatus\" <>", value, "martialstatus");
            return (Criteria) this;
        }

        public Criteria andMartialstatusGreaterThan(Short value) {
            addCriterion("\"martialStatus\" >", value, "martialstatus");
            return (Criteria) this;
        }

        public Criteria andMartialstatusGreaterThanOrEqualTo(Short value) {
            addCriterion("\"martialStatus\" >=", value, "martialstatus");
            return (Criteria) this;
        }

        public Criteria andMartialstatusLessThan(Short value) {
            addCriterion("\"martialStatus\" <", value, "martialstatus");
            return (Criteria) this;
        }

        public Criteria andMartialstatusLessThanOrEqualTo(Short value) {
            addCriterion("\"martialStatus\" <=", value, "martialstatus");
            return (Criteria) this;
        }

        public Criteria andMartialstatusIn(List<Short> values) {
            addCriterion("\"martialStatus\" in", values, "martialstatus");
            return (Criteria) this;
        }

        public Criteria andMartialstatusNotIn(List<Short> values) {
            addCriterion("\"martialStatus\" not in", values, "martialstatus");
            return (Criteria) this;
        }

        public Criteria andMartialstatusBetween(Short value1, Short value2) {
            addCriterion("\"martialStatus\" between", value1, value2, "martialstatus");
            return (Criteria) this;
        }

        public Criteria andMartialstatusNotBetween(Short value1, Short value2) {
            addCriterion("\"martialStatus\" not between", value1, value2, "martialstatus");
            return (Criteria) this;
        }

        public Criteria andActiveflagIsNull() {
            addCriterion("\"activeFlag\" is null");
            return (Criteria) this;
        }

        public Criteria andActiveflagIsNotNull() {
            addCriterion("\"activeFlag\" is not null");
            return (Criteria) this;
        }

        public Criteria andActiveflagEqualTo(Short value) {
            addCriterion("\"activeFlag\" =", value, "activeflag");
            return (Criteria) this;
        }

        public Criteria andActiveflagNotEqualTo(Short value) {
            addCriterion("\"activeFlag\" <>", value, "activeflag");
            return (Criteria) this;
        }

        public Criteria andActiveflagGreaterThan(Short value) {
            addCriterion("\"activeFlag\" >", value, "activeflag");
            return (Criteria) this;
        }

        public Criteria andActiveflagGreaterThanOrEqualTo(Short value) {
            addCriterion("\"activeFlag\" >=", value, "activeflag");
            return (Criteria) this;
        }

        public Criteria andActiveflagLessThan(Short value) {
            addCriterion("\"activeFlag\" <", value, "activeflag");
            return (Criteria) this;
        }

        public Criteria andActiveflagLessThanOrEqualTo(Short value) {
            addCriterion("\"activeFlag\" <=", value, "activeflag");
            return (Criteria) this;
        }

        public Criteria andActiveflagIn(List<Short> values) {
            addCriterion("\"activeFlag\" in", values, "activeflag");
            return (Criteria) this;
        }

        public Criteria andActiveflagNotIn(List<Short> values) {
            addCriterion("\"activeFlag\" not in", values, "activeflag");
            return (Criteria) this;
        }

        public Criteria andActiveflagBetween(Short value1, Short value2) {
            addCriterion("\"activeFlag\" between", value1, value2, "activeflag");
            return (Criteria) this;
        }

        public Criteria andActiveflagNotBetween(Short value1, Short value2) {
            addCriterion("\"activeFlag\" not between", value1, value2, "activeflag");
            return (Criteria) this;
        }

        public Criteria andAdddatetimeIsNull() {
            addCriterion("\"addDateTime\" is null");
            return (Criteria) this;
        }

        public Criteria andAdddatetimeIsNotNull() {
            addCriterion("\"addDateTime\" is not null");
            return (Criteria) this;
        }

        public Criteria andAdddatetimeEqualTo(Date value) {
            addCriterion("\"addDateTime\" =", value, "adddatetime");
            return (Criteria) this;
        }

        public Criteria andAdddatetimeNotEqualTo(Date value) {
            addCriterion("\"addDateTime\" <>", value, "adddatetime");
            return (Criteria) this;
        }

        public Criteria andAdddatetimeGreaterThan(Date value) {
            addCriterion("\"addDateTime\" >", value, "adddatetime");
            return (Criteria) this;
        }

        public Criteria andAdddatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("\"addDateTime\" >=", value, "adddatetime");
            return (Criteria) this;
        }

        public Criteria andAdddatetimeLessThan(Date value) {
            addCriterion("\"addDateTime\" <", value, "adddatetime");
            return (Criteria) this;
        }

        public Criteria andAdddatetimeLessThanOrEqualTo(Date value) {
            addCriterion("\"addDateTime\" <=", value, "adddatetime");
            return (Criteria) this;
        }

        public Criteria andAdddatetimeIn(List<Date> values) {
            addCriterion("\"addDateTime\" in", values, "adddatetime");
            return (Criteria) this;
        }

        public Criteria andAdddatetimeNotIn(List<Date> values) {
            addCriterion("\"addDateTime\" not in", values, "adddatetime");
            return (Criteria) this;
        }

        public Criteria andAdddatetimeBetween(Date value1, Date value2) {
            addCriterion("\"addDateTime\" between", value1, value2, "adddatetime");
            return (Criteria) this;
        }

        public Criteria andAdddatetimeNotBetween(Date value1, Date value2) {
            addCriterion("\"addDateTime\" not between", value1, value2, "adddatetime");
            return (Criteria) this;
        }

        public Criteria andAdduserIsNull() {
            addCriterion("\"addUser\" is null");
            return (Criteria) this;
        }

        public Criteria andAdduserIsNotNull() {
            addCriterion("\"addUser\" is not null");
            return (Criteria) this;
        }

        public Criteria andAdduserEqualTo(String value) {
            addCriterion("\"addUser\" =", value, "adduser");
            return (Criteria) this;
        }

        public Criteria andAdduserNotEqualTo(String value) {
            addCriterion("\"addUser\" <>", value, "adduser");
            return (Criteria) this;
        }

        public Criteria andAdduserGreaterThan(String value) {
            addCriterion("\"addUser\" >", value, "adduser");
            return (Criteria) this;
        }

        public Criteria andAdduserGreaterThanOrEqualTo(String value) {
            addCriterion("\"addUser\" >=", value, "adduser");
            return (Criteria) this;
        }

        public Criteria andAdduserLessThan(String value) {
            addCriterion("\"addUser\" <", value, "adduser");
            return (Criteria) this;
        }

        public Criteria andAdduserLessThanOrEqualTo(String value) {
            addCriterion("\"addUser\" <=", value, "adduser");
            return (Criteria) this;
        }

        public Criteria andAdduserLike(String value) {
            addCriterion("\"addUser\" like", value, "adduser");
            return (Criteria) this;
        }

        public Criteria andAdduserNotLike(String value) {
            addCriterion("\"addUser\" not like", value, "adduser");
            return (Criteria) this;
        }

        public Criteria andAdduserIn(List<String> values) {
            addCriterion("\"addUser\" in", values, "adduser");
            return (Criteria) this;
        }

        public Criteria andAdduserNotIn(List<String> values) {
            addCriterion("\"addUser\" not in", values, "adduser");
            return (Criteria) this;
        }

        public Criteria andAdduserBetween(String value1, String value2) {
            addCriterion("\"addUser\" between", value1, value2, "adduser");
            return (Criteria) this;
        }

        public Criteria andAdduserNotBetween(String value1, String value2) {
            addCriterion("\"addUser\" not between", value1, value2, "adduser");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNull() {
            addCriterion("\"updateTime\" is null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNotNull() {
            addCriterion("\"updateTime\" is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeEqualTo(Date value) {
            addCriterion("\"updateTime\" =", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotEqualTo(Date value) {
            addCriterion("\"updateTime\" <>", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThan(Date value) {
            addCriterion("\"updateTime\" >", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("\"updateTime\" >=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThan(Date value) {
            addCriterion("\"updateTime\" <", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("\"updateTime\" <=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIn(List<Date> values) {
            addCriterion("\"updateTime\" in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotIn(List<Date> values) {
            addCriterion("\"updateTime\" not in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeBetween(Date value1, Date value2) {
            addCriterion("\"updateTime\" between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("\"updateTime\" not between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateuserIsNull() {
            addCriterion("\"updateUser\" is null");
            return (Criteria) this;
        }

        public Criteria andUpdateuserIsNotNull() {
            addCriterion("\"updateUser\" is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateuserEqualTo(String value) {
            addCriterion("\"updateUser\" =", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserNotEqualTo(String value) {
            addCriterion("\"updateUser\" <>", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserGreaterThan(String value) {
            addCriterion("\"updateUser\" >", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserGreaterThanOrEqualTo(String value) {
            addCriterion("\"updateUser\" >=", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserLessThan(String value) {
            addCriterion("\"updateUser\" <", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserLessThanOrEqualTo(String value) {
            addCriterion("\"updateUser\" <=", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserLike(String value) {
            addCriterion("\"updateUser\" like", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserNotLike(String value) {
            addCriterion("\"updateUser\" not like", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserIn(List<String> values) {
            addCriterion("\"updateUser\" in", values, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserNotIn(List<String> values) {
            addCriterion("\"updateUser\" not in", values, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserBetween(String value1, String value2) {
            addCriterion("\"updateUser\" between", value1, value2, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserNotBetween(String value1, String value2) {
            addCriterion("\"updateUser\" not between", value1, value2, "updateuser");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.UserDetail
     *
     * @mbggenerated do_not_delete_during_merge Sun May 09 19:28:04 JST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.UserDetail
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}