package ly.jp.application.model.entity;

import java.util.Date;

public class Usermst {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.UserMst.userID
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.UserMst.userName
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.UserMst.password
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.UserMst.addDateTime
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    private Date adddatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.UserMst.addUser
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    private String adduser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.UserMst.updateTime
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.UserMst.updateUser
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    private String updateuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.UserMst.userID
     *
     * @return the value of public.UserMst.userID
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.UserMst.userID
     *
     * @param userid the value for public.UserMst.userID
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.UserMst.userName
     *
     * @return the value of public.UserMst.userName
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.UserMst.userName
     *
     * @param username the value for public.UserMst.userName
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.UserMst.password
     *
     * @return the value of public.UserMst.password
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.UserMst.password
     *
     * @param password the value for public.UserMst.password
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.UserMst.addDateTime
     *
     * @return the value of public.UserMst.addDateTime
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public Date getAdddatetime() {
        return adddatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.UserMst.addDateTime
     *
     * @param adddatetime the value for public.UserMst.addDateTime
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public void setAdddatetime(Date adddatetime) {
        this.adddatetime = adddatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.UserMst.addUser
     *
     * @return the value of public.UserMst.addUser
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public String getAdduser() {
        return adduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.UserMst.addUser
     *
     * @param adduser the value for public.UserMst.addUser
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public void setAdduser(String adduser) {
        this.adduser = adduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.UserMst.updateTime
     *
     * @return the value of public.UserMst.updateTime
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.UserMst.updateTime
     *
     * @param updatetime the value for public.UserMst.updateTime
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.UserMst.updateUser
     *
     * @return the value of public.UserMst.updateUser
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public String getUpdateuser() {
        return updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.UserMst.updateUser
     *
     * @param updateuser the value for public.UserMst.updateUser
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public void setUpdateuser(String updateuser) {
        this.updateuser = updateuser;
    }
}