package ly.jp.application.model.entity;

import java.util.Date;

public class Userdetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.UserDetail.userID
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.UserDetail.userName
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.UserDetail.katakanaName
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    private String katakananame;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.UserDetail.sex
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.UserDetail.address
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.UserDetail.age
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    private Short age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.UserDetail.birthdate
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    private Date birthdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.UserDetail.phonenumeric
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    private Long phonenumeric;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.UserDetail.weChatnumeric
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    private String wechatnumeric;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.UserDetail.mailAddress
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    private String mailaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.UserDetail.position
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.UserDetail.nationality
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    private String nationality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.UserDetail.martialStatus
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    private Short martialstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.UserDetail.activeFlag
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    private Short activeflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.UserDetail.addDateTime
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    private Date adddatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.UserDetail.addUser
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    private String adduser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.UserDetail.updateTime
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.UserDetail.updateUser
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    private String updateuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.UserDetail.weChatQRcode
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    private byte[] wechatqrcode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.UserDetail.userID
     *
     * @return the value of public.UserDetail.userID
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.UserDetail.userID
     *
     * @param userid the value for public.UserDetail.userID
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.UserDetail.userName
     *
     * @return the value of public.UserDetail.userName
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.UserDetail.userName
     *
     * @param username the value for public.UserDetail.userName
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.UserDetail.katakanaName
     *
     * @return the value of public.UserDetail.katakanaName
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public String getKatakananame() {
        return katakananame;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.UserDetail.katakanaName
     *
     * @param katakananame the value for public.UserDetail.katakanaName
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public void setKatakananame(String katakananame) {
        this.katakananame = katakananame;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.UserDetail.sex
     *
     * @return the value of public.UserDetail.sex
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.UserDetail.sex
     *
     * @param sex the value for public.UserDetail.sex
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.UserDetail.address
     *
     * @return the value of public.UserDetail.address
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.UserDetail.address
     *
     * @param address the value for public.UserDetail.address
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.UserDetail.age
     *
     * @return the value of public.UserDetail.age
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public Short getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.UserDetail.age
     *
     * @param age the value for public.UserDetail.age
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public void setAge(Short age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.UserDetail.birthdate
     *
     * @return the value of public.UserDetail.birthdate
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public Date getBirthdate() {
        return birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.UserDetail.birthdate
     *
     * @param birthdate the value for public.UserDetail.birthdate
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.UserDetail.phonenumeric
     *
     * @return the value of public.UserDetail.phonenumeric
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public Long getPhonenumeric() {
        return phonenumeric;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.UserDetail.phonenumeric
     *
     * @param phonenumeric the value for public.UserDetail.phonenumeric
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public void setPhonenumeric(Long phonenumeric) {
        this.phonenumeric = phonenumeric;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.UserDetail.weChatnumeric
     *
     * @return the value of public.UserDetail.weChatnumeric
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public String getWechatnumeric() {
        return wechatnumeric;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.UserDetail.weChatnumeric
     *
     * @param wechatnumeric the value for public.UserDetail.weChatnumeric
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public void setWechatnumeric(String wechatnumeric) {
        this.wechatnumeric = wechatnumeric;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.UserDetail.mailAddress
     *
     * @return the value of public.UserDetail.mailAddress
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public String getMailaddress() {
        return mailaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.UserDetail.mailAddress
     *
     * @param mailaddress the value for public.UserDetail.mailAddress
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public void setMailaddress(String mailaddress) {
        this.mailaddress = mailaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.UserDetail.position
     *
     * @return the value of public.UserDetail.position
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.UserDetail.position
     *
     * @param position the value for public.UserDetail.position
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public void setPosition(String position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.UserDetail.nationality
     *
     * @return the value of public.UserDetail.nationality
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.UserDetail.nationality
     *
     * @param nationality the value for public.UserDetail.nationality
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public void setNationality(String nationality) {
        this.nationality = nationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.UserDetail.martialStatus
     *
     * @return the value of public.UserDetail.martialStatus
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public Short getMartialstatus() {
        return martialstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.UserDetail.martialStatus
     *
     * @param martialstatus the value for public.UserDetail.martialStatus
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public void setMartialstatus(Short martialstatus) {
        this.martialstatus = martialstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.UserDetail.activeFlag
     *
     * @return the value of public.UserDetail.activeFlag
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public Short getActiveflag() {
        return activeflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.UserDetail.activeFlag
     *
     * @param activeflag the value for public.UserDetail.activeFlag
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public void setActiveflag(Short activeflag) {
        this.activeflag = activeflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.UserDetail.addDateTime
     *
     * @return the value of public.UserDetail.addDateTime
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public Date getAdddatetime() {
        return adddatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.UserDetail.addDateTime
     *
     * @param adddatetime the value for public.UserDetail.addDateTime
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public void setAdddatetime(Date adddatetime) {
        this.adddatetime = adddatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.UserDetail.addUser
     *
     * @return the value of public.UserDetail.addUser
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public String getAdduser() {
        return adduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.UserDetail.addUser
     *
     * @param adduser the value for public.UserDetail.addUser
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public void setAdduser(String adduser) {
        this.adduser = adduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.UserDetail.updateTime
     *
     * @return the value of public.UserDetail.updateTime
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.UserDetail.updateTime
     *
     * @param updatetime the value for public.UserDetail.updateTime
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.UserDetail.updateUser
     *
     * @return the value of public.UserDetail.updateUser
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public String getUpdateuser() {
        return updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.UserDetail.updateUser
     *
     * @param updateuser the value for public.UserDetail.updateUser
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public void setUpdateuser(String updateuser) {
        this.updateuser = updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.UserDetail.weChatQRcode
     *
     * @return the value of public.UserDetail.weChatQRcode
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public byte[] getWechatqrcode() {
        return wechatqrcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.UserDetail.weChatQRcode
     *
     * @param wechatqrcode the value for public.UserDetail.weChatQRcode
     *
     * @mbggenerated Sun May 09 19:28:04 JST 2021
     */
    public void setWechatqrcode(byte[] wechatqrcode) {
        this.wechatqrcode = wechatqrcode;
    }
}